function devol(){var Q='',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',jb='"><\/script>',$='#',Gb='&',nc='.cache.html',ab='/',mb='//',_b='2219CE2B2C860AB6927A0B06EBCA6A71',ac='25CBD715DEFE3393D463ACF3D63D06B0',cc='322764F61CEEB1B41C3A19716D7B947E',dc='50984E7EA0C837AC1779DBFF3B3B2524',ec='5184E3D58D81E9597BD6A6420E12777C',fc='5707C98B179DAAD5307FFA0A3DD127F9',gc='64C9FC68E85CCA287C4B61F4180D03E4',hc='7638356ADDD4E774636BDD6375DFBA1D',ic='95C4F99837627A6309BF013447C98E06',mc=':',qb='::',vc='<script defer="defer">devol.onInjectionDone(\'devol\')<\/script>',ib='<script id="',tb='=',_='?',vb='Bad handler "',uc='DOMContentLoaded',jc='E0F3D4530B9484BAA5278C79DFE29652',kc='F4D3C8EE7E3A75855C33C392598C5062',lc='FCC5D4654D4E6116CEF79486CF4DE927',kb='SCRIPT',Jb='Unexpected exception in locale detection, using default: ',Ib='_',Hb='__gwt_Locale',hb='__gwt_marker_devol',lb='base',db='baseUrl',U='begin',T='bootstrap',cb='clear.cache.gif',sb='content',Eb='default',R='devol',fb='devol.nocache.js',pb='devol::',bc='en',Z='end',Vb='gecko',Wb='gecko1_8',V='gwt.codesvr=',W='gwt.hosted=',X='gwt.hybrid',oc='gwt/clean/clean.css',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',tc='head',Zb='hosted.html?devol',sc='href',Ub='ie6',Tb='ie8',Sb='ie9',zb='iframe',bb='img',Ab="javascript:''",pc='link',Yb='loadExternalRefs',Db='locale',Fb='locale=',nb='meta',Kb='mobile.user.agent',Lb='mobilesafari',Cb='moduleRequested',Y='moduleStartup',Rb='msie',ob='name',Mb='not_mobile',Ob='opera',Bb='position:absolute;width:0;height:0;border:none',qc='rel',Qb='safari',eb='script',$b='selectingPermutation',S='startup',rc='stylesheet',gb='undefined',Xb='unknown',Nb='user.agent',Pb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=Q,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:U});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(V)!=-1||(c.indexOf(W)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(X)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(R);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return I(a)}}devol=null;c.gwtOnLoad(z,R,t,y);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Z})}}
function D(){function e(a){var b=a.lastIndexOf($);if(b==-1){b=a.length}var c=a.indexOf(_);if(c==-1){c=a.length}var d=a.lastIndexOf(ab,Math.min(c,b));return d>=0?a.substring(0,d+1):Q}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(bb);b.src=a+cb;a=e(b.src)}return a}
function g(){var a=G(db);if(a!=null){return a}return Q}
function h(){var a=n.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(fb)!=-1){return e(a[b].src)}}return Q}
function i(){var a;if(typeof isBodyLoaded==gb||!isBodyLoaded()){var b=hb;var c;n.write(ib+b+jb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=kb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return Q}
function j(){var a=n.getElementsByTagName(lb);if(a.length>0){return a[a.length-1].href}return Q}
function k(){var a=n.location;return a.href==a.protocol+mb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==Q){l=h()}if(l==Q){l=i()}if(l==Q){l=j()}if(l==Q&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(nb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(ob),g;if(f){f=f.replace(pb,Q);if(f.indexOf(qb)>=0){continue}if(f==rb){g=e.getAttribute(sb);if(g){var h,i=g.indexOf(tb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=Q}u[f]=h}}else if(f==ub){g=e.getAttribute(sb);if(g){try{A=eval(g)}catch(a){alert(vb+g+wb)}}}else if(f==xb){g=e.getAttribute(sb);if(g){try{z=eval(g)}catch(a){alert(vb+g+yb)}}}}}}
function F(a,b){return b in v[a]}
function G(a){var b=u[a];return b==null?null:b}
function H(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function I(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var J;function K(){if(!J){J=true;var a=n.createElement(zb);a.src=Ab;a.id=R;a.style.cssText=Bb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Cb});a.contentWindow.location.replace(t+M)}}
w[Db]=function(){var b=null;var c=Eb;try{if(!b){var d=location.search;var e=d.indexOf(Fb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Gb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=G(Db)}if(!b){b=m[Hb]}if(b){c=b}while(b&&!F(Db,b)){var h=b.lastIndexOf(Ib);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Jb+a)}m[Hb]=c;return b||Eb};v[Db]={'default':0,en:1};w[Kb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Lb:Mb};v[Kb]={mobilesafari:0,not_mobile:1};w[Nb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ob)!=-1}())return Ob;if(function(){return b.indexOf(Pb)!=-1}())return Qb;if(function(){return b.indexOf(Rb)!=-1&&n.documentMode>=9}())return Sb;if(function(){return b.indexOf(Rb)!=-1&&n.documentMode>=8}())return Tb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Ub;if(function(){return b.indexOf(Vb)!=-1}())return Wb;return Xb};v[Nb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};devol.onScriptLoad=function(){if(J){r=true;C()}};devol.onInjectionDone=function(){q=true;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Yb,millis:(new Date).getTime(),type:Z});C()};E();D();var L;var M;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(R))){m.location.reload();return}M=Zb;L=Q}o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:$b});if(!B()){try{H([Eb,Mb,Wb],_b);H([Eb,Mb,Tb],ac);H([bc,Mb,Qb],cc);H([bc,Mb,Tb],dc);H([bc,Mb,Sb],ec);H([bc,Mb,Wb],fc);H([bc,Mb,Ob],gc);H([Eb,Lb,Qb],hc);H([Eb,Mb,Sb],ic);H([Eb,Mb,Ob],jc);H([Eb,Mb,Qb],kc);H([bc,Lb,Qb],lc);L=x[I(Db)][I(Kb)][I(Nb)];var N=L.indexOf(mc);if(N!=-1){y=Number(L.substring(N+1));L=L.substring(0,N)}M=L+nc}catch(a){return}}var O;function P(){if(!s){s=true;if(!__gwt_stylesLoaded[oc]){var a=n.createElement(pc);__gwt_stylesLoaded[oc]=a;a.setAttribute(qc,rc);a.setAttribute(sc,t+oc);n.getElementsByTagName(tc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(uc,P,false)}if(O){clearInterval(O)}}}
if(n.addEventListener){n.addEventListener(uc,function(){K();P()},false)}var O=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K();P()}},50);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Z});o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Yb,millis:(new Date).getTime(),type:U});n.write(vc)}
devol();